### ISSUE TITLE
Duration is long now

### ISSUE THREAD

**Issue by Muschasgrazias** [behalf-oss/behave2cucumber#4]

**Comment by andreybehalf** [comment]
Do you want to create pull request with the things that need to be updated?
Thanks

**Comment by Muschasgrazias** [comment]
Hi,
Is it okay if I just post it here?
```
# line 29
if json_nodes[index] == 'steps':
     if 'result' in item:
        duration = item["result"].pop('duration')
        if duration < 1:
            duration = 1
        else:
            duration = int(duration)
        item["result"]["duration"] = duration
```

**Comment by andreybehalf** [comment]
Yeah, no problem, it just will take time to test it.

**Comment by Muschasgrazias** [comment]
Hi,
Update: JSON files want the duration in ns
So actually what we have to do is: 
`item["result"]["duration"] = item["result"].pop('duration')*1000000000`

Kind regards

**Comment by andreybehalf** [comment]
Yeah actually I've got the same conclusion 2 days back 👍 . I've updated the module in pip so just upgrade the version to 1.0.2.2 and it will have optional variable that will convert the duration. 
Thanks for the help and contribution mate!
